= Описание работы БП "Выгрузка данных удаленному серверу"

БП _Выгрузка данных удаленному серверу_ выполняет следующие операции:

. Отправляет на удаленный сервер подтверждения о полученных _Заданиях интеграции_.
.. Выбирает карточки Задания интеграции со статусом задания на площадке-отправителе `Отправлено`/`Sent`.
.. Отправляет на удаленный сервер XML-документ, содержащий подтверждение о получении Задания интеграции.
.. Изменяет статус задания на площадке-отправителе на значение `Подтверждено`/`Confirm`.
. Выполняет поиск Заданий интеграции со статусом задания на площадке-отправителе `Создано` или `Передается`.
. Передает найденные Задания интеграции на удаленные сервера.
.. Если _Задания интеграции_ в статусе `Создано` на площадке-отправителе:
... Статус задания на площадке-получателе устанавливается в значение `Принимается`/`Receiving`.
... Передает на удаленный сервер Задание интеграции.
+
Для отправки используется выбранный в настройках обработчика транспорт.
... Статус задания на площадке-отправителе устанавливается в значение `Передается`/`Sending`.
. Передает бинарные данные файлов из Задания интеграции на удаленный сервер.
.. Выполняет поиск файлов со статусом переноса `Необходим перенос`/`NeedTransfer`.
.. Передает файлы на удаленный сервер.
+
Статус переноса файла на удаленный сервер может принять одно из следующих значений:

* `Перенесен на удалённый сервер`/`Transfered` -- если файл успешно перенесен.
* `Найден подобный на удалённом сервере`/`FoundSame` -- если на удаленном сервере существует файл с идентичной хеш-суммой.
+
[NOTE]
====
Информация о хеш-суммах загруженных файлов хранится в справочнике _Каталог файлов_.
====
+
* `Не изменен на удалённом сервере`/`NotChanged` -- если на удаленном сервере существует идентичный файл с идентичной хеш-суммой.
+
.. Статус задания на площадке-отправителе изменяется на значение `Отправлено`/`Sent`. Статус задания на площадке-получателе устанавливается в значение `Получено`/`Received`.
