= Общие сведения о модуле

"Модуль межфилиального обмена" (МФО) -- дополнение к {dv} для организации обмена карточками между несколькими не связанными серверами {dv}.

МФО обеспечивает синхронизацию карточек, но не справочников {dv}. Для репликации справочников используйте модуль "xref:replication::index.adoc[{dv} 5. Модуль репликации справочников]" или другие инструменты.

[NOTE]
====
Для работы МФО необходимо, чтобы данные определённых справочников, размещенных на серверах {dv}, были синхронизированы. Подробности в пункте xref:admin:synchcronize-directories.adoc[Синхронизация справочников {dv}].
====

== Назначение и функции

МФО предоставляет следующие функции:

* Фоновая передача карточек при выполнении операций с ними.
* Передача связанных карточек.
* Передача файлов в отдельном потоке.
* Автоматическое разрешение конфликтных ситуаций при загрузке карточек на удалённом сервере.
* Протоколирование операций на этапах выгрузки, передачи и импорта карточек.

МФО предлагается организациям с распределенной структурой, в которых сотрудникам удалённых офисов требуется решать общие задачи при работе в {dv}.
