= Необходимые ресурсы

[#hardware]
== Необходимое техническое обеспечение

Специальные требования к аппаратному обеспечению не предъявляются.

[#software]
== Необходимое программное обеспечение

.Модули {dv}:
. Серверная и клиентская части модуля _{dv} 5. {pl}_ версии {pl-req} и выше.
. Серверная и клиентская части приложения _{dv} 5. {dm}_ версии {dm-req} и выше.
. Серверная и клиентская части модуля _{dv} 5. {wf}_ версии {wf-req} и выше.
. Серверная и клиентская части модуля _{dv} 5. {ad}_ версии {ad-req} и выше.
. Серверная и клиентская части приложения _{dv} 5. {to}_ версии {to-req} и выше.
. Серверная и клиентская части модуля _{dv} 5. {wincl}_ версии {win-req} и выше.

[#network]
== Требования к каналам связи

Администратор должен обеспечить возможность передачи данных по локальной сети между серверами {dv}, участвующими в межфилиальном обмене.

[#license]
== Лицензия

Для работы с модулем _{dv} 5. Модуль межфилиального обмена_ лицензия на систему {dv} должна содержать дополнительную опцию _{dv} Replication_. Лицензионная опция должна быть у каждого сервера {dv}, участвующего в межфилиальном обмене.
