= Разработка компонента определения состава передачи

_Компонент определения состава передачи_ должен предоставить список идентификаторов карточек, которые должны быть переданы на удаленные сервера {dv}.

Программный класс данного должен реализовывать интерфейс `xref:IEventResolver_IN.adoc[IEventResolver]` с единственным методом `ResolveEvent`. Данный метод должен добавить идентификаторы отправляемых карточек в переменную `Cards` объекта `e`, переданного в первом параметре метода.

Список отправляемых данных должен быть минимально достаточным, т.к. большое число передаваемых данных скажется на конечной производительности, а недостаточность этих данных -- на невозможности работы с карточками.

Следующий код демонстрирует пример реализации _компонента определения состава передачи_. В компоненте, в пакет отправляемых данных, добавляется только карточка, из которой было вызвано событие обмена.

[source,csharp]
----
using Docsvision.Replication.Extensibility;
using Docsvision.Replication.Interfaces;

namespace Replication.Demo
{

    [ResName("Пример. Определение состава передачи")]
    public class EventResolver : BaseHandler, IEventResolver <.>
    {
        public void ResolveEvent(IExchangeEvent e, out bool cancel)
        {

        if (!e.Cards.Contains(e.ObjectId)) <.>
        {
            e.Cards.Add(e.ObjectId);
        }

        cancel = false; <.>
        }
    }
}
----
<.> Описание, переданное в `DescriptionAttribute`, будет выводиться в выпадающем списке Справочника настроек МФО.
<.> Если в списке карточек отсутствует карточка вызвавшая событие, она будет добавлена.
<.> Обработку не останавливать.