= ExchangeScenario -- класс

Класс `ExchangeScenario` предоставляет параметры _сценария обмена_, определенного в _Справочнике настроек МФО_.

* *Пространство имён:* `{dv}.Replication.ObjectModel`
* *Сборка:* `{dv}.Replication.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
public class ExchangeScenario : ObjectBase, IExchangeScenario
----

== Свойства

[cols=",",options="header"]
|===
|Имя |Описание

|`ConflictHandler`
a|Задает или возвращает название класса, реализующего _компонент разрешения конфликтов_. _Не используется в текущей реализации._

*Тип*: `System.String`

|`ExportDatasetHandler`
a|Задает или возвращает название класса, реализующего _компонент определения состава передачи_.

*Тип*: `System.String`

|`ExportHandler`
a|Задает или возвращает название класса, реализующего _компонент выгрузки_.

*Тип*: `System.String.`

|`ImportHandler`
a|Задает или возвращает название класса, реализующего _компонент загрузки_.

*Тип*: `System.String`

|`Kind`
a|Задает или возвращает идентификатор вида карточки, для которой предназначен данный _сценарий обмена_.

*Тип* `System.Guid`

|`Name`
a|Задает или возвращает название _сценария обмена_.

*Тип* `System.String`

|`PostExportHandler`
a|Задает или возвращает идентификатор бизнес-процесса, который будет запущен на сервере получателя после завершения работы _компонента загрузки_.

*Тип* `System.Guid`

|`RecipientsHandler`
a|Задает или возвращает название класса, реализующего _компонент определения адресатов_.

*Тип* `System.String`

|===

== Поля

[cols=",",options="header"]
|===
|Имя |Описание

|`ConflictHandlerProperty`
a|Определяет свойство "Алгоритм разрешения конфликтов".

*Тип*: `{dv}.Platform.ObjectModel.ObjectProperty`

|`ExportDatasetHandlerProperty`
a|Определяет свойство "Обработчик определяющий, что выгружать".

*Тип*: `{dv}.Platform.ObjectModel.ObjectProperty`

|`ExportHandlerProperty`
a|Определяет свойство "Обработчик выполняющий выгрузку данных".

*Тип*: `{dv}.Platform.ObjectModel.ObjectProperty`

|`ImportHandlerProperty`
a|Определяет свойство "Обработчик загрузки данных".

*Тип*: `{dv}.Platform.ObjectModel.ObjectProperty`

|`KindProperty`
a|Определяет свойство "Вид карточки".

*Тип*: `{dv}.Platform.ObjectModel.ObjectProperty`

|`NameProperty`
a|Определяет свойство "Имя сценария".

*Тип*: `{dv}.Platform.ObjectModel.ObjectProperty`

|`PostExportHandlerProperty`
a|Определяет свойство "Обработчик после выгрузки".

*Тип*: `{dv}.Platform.ObjectModel.ObjectProperty`

|`RecipientsHandlerProperty`
a|Определяет свойство "Обработчик вычисления адресатов".

*Тип*: `{dv}.Platform.ObjectModel.ObjectProperty`

|===
