= FileReplicationTransfer -- класс

Класс `FileReplicationTransfer` предоставляет метод записи _Задания интеграции_, подготовленного к отправке на удаленный сервер, в файл.

* *Пространство имён:* `{dv}.Replication.Extensibility.Transfers`
* *Сборка:* `{dv}.Replication.Extensibility.dll`

== Синтаксис

[source,csharp]
----
public class FileReplicationTransfer : IReplicationTransfer
----

== Конструкторы

[cols="40%,60%",options="header"]
|===
|Имя |Описание

|`FileReplicationTransfer(String, Guid)`
a|Инициализирует новый экземпляр класса `FileReplicationTransfer`.

.Параметры:
* `basePath` -- полный путь для выгрузки файла
* `remoteServerId` -- идентификатор удаленного сервера

|===

== Свойства

[cols="40%,60%",options="header"]
|===
|Имя |Описание

|`RemoteServerId` |Возвращает идентификатор удаленного сервера.

*Тип*: `System.Guid`.

|===

== Методы

[cols="40%,60%",options="header"]
|===
|Имя |Описание

|`Transfer(String)`
a|Передает на удаленный сервер {dv} _Задание интеграции_, содержащее данные карточек, атрибуты файлов карточек и бинарные данные файлов.

.Параметры:
* `data` -- строка, содержащая XML данные карточки _Задания интеграции_

|`TransferIntegrationTask(Guid, String)`
|_Не используется в текущей реализации. При попытке обращения будет возвращено исключение._

|`TransferIntegrationTaskFile(Guid, Guid, FileData, ref Boolean)`
|_Не используется в текущей реализации. При попытке обращения будет возвращено исключение._

|===

== Заметки

Итоговый файл будет сформирован по следующему пути `\{basePath}/\{remoteServerId}/\{yyMMddhhmmss}.xml`, где:

* `basePath` -- значение параметра `basePath`, переданного в конструктор класса;
* `remoteServerId` -- значение параметра `remoteServerId`, переданного в конструктор класса и приведенного к строковому виду;
* `yyMMddhhmmss` -- текущее время, приведенное к формату `yyMMddhhmmss`.

== Примеры

Далее приведена часть бизнес-процесса "Выгрузка данных удаленному серверу XX", который отвечает за передачу _Задания интеграции_ удаленному серверу. Данный экземпляр бизнес-процесса выполняет запись заданий в папку `Z:\Export` (полный путь будет сформирован по правилу, описанному выше). Предполагается, что _получатель_ самостоятельно запросит содержимое нужной папки и выполнит обработку имеющихся там _Заданий интеграции_.

[source,csharp]
----
<.>

IReplicationLibService replicationLibService = Context.GetService<IReplicationLibService>(); <.>

FileReplicationTransfer transfer = new FileReplicationTransfer(@"z:\export", remoteServerID); <.>

replicationLibService.ReplicateIntegrationTasks(transfer, remoteServerID); <.>
----
<.> Начало скрипта бизнес-процесса _Выгрузка данных удаленному серверу XX_ совпадает с шаблоном _Выгрузка данных удаленному серверу_.
<.> Получение сервиса репликации.
<.> Инициализация класса, отвечающего за передачу _Задания интеграции_. `remoteServerID` -- идентификатор удаленного сервера, полученный из параметров бизнес процесса.
<.> Выполнение передачи задания.

На стороне _получателя_ необходимо осуществить загрузку заданий из папки, в которую осуществляется сброс _Заданий интеграции_. В простейшем случае код бизнес-процесса, осуществляющего загрузку одного задания будет выглядеть следующим образом:

[source,csharp]
----
using System;
using System.Xml;

using Docsvision.Workflow.Objects;
using Docsvision.Workflow.Runtime;
using Docsvision.Workflow.Gates;
using Docsvision.Platform.HelperAPI;
using Docsvision.Platform.ObjectManager;

namespace DVScriptHost
{
 class DVScript
 {
  public void Execute (ProcessInfo process, PassState passInfo)
  {

   string data = System.IO.File.ReadAllText(@"z:\export\{313f9565-c312-47fb-bf6f-b35d9e2949e9}\141014031005.xml"); <.>
   
   ExtensionMethod extensionMethod = process.Session.ExtensionManager.GetExtensionMethod("ReplicationServerExtension", "ImportIntegrationTasks"); <.>
   extensionMethod.Parameters.AddNew("data", ParameterValueType.String, data);
   extensionMethod.Execute();
  }
 }
}
----
<.> Путь к файлу, содержащему выгрузку карточки _Задание интеграции_. `313f9565-c312-47fb-bf6f-b35d9e2949e9` -- идентификатор сервера получателя.
<.> Вызов серверного метода, выполняющего загрузку _Заданий интеграции_.
