= IDataImporter - интерфейс

Описывает сигнатуру класса _компонента загрузки_, отвечающего за загрузку данных на стороне _получателя_.

* *Пространство имен:* {dv}.Replication.Interfaces
* *Сборка:* `{dv}.Replication.Interfaces.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
public interface IDataImporter
----

== Методы

[cols="34%,66%",options="header"]
|===
|Имя |Описание
|CanImportData(IIntegrationTask, String, IEnumerable<Guid>, out IEnumerable<Guid>) a|
Проверяет возможность импорта данных из Задания интеграции.

Параметры:

* task - данные обрабатываемого _Задания интеграции_
* Data - XML-данные загружаемых карточек
* filesId -- идентификаторы загружаемых файлов
* filteredFilesIds -- идентификаторы файлов, загрузка которых возможна

Тип: System.Boolean

Результат проверки: true -- загрузка данных возможна; false -- загрузка данных невозможна

|ImportData(IIntegrationTask, String) a|
При переопределении в производном классе выполняет загрузку карточек, полученных из _Задания интеграции_. Метод может реализовывать механизм разрешение конфликтов.

Параметры:

* task - данные обрабатываемого _Задания интеграции_
* Data - XML-данные загружаемых карточек

|===

== Заметки

Пример реализации смотрите в разделе xref:UseAPIDataImporter.adoc[Разработка компонента загрузки].
