= IReplicationService -- интерфейс

Сервис объектной модели библиотеки "Модуль межфилиального обмена", предназначенный для обработки _Заданий интеграции_.

* *Пространство имён:* `{dv}.Replication.Interfaces`
* *Сборка:* `{dv}.Replication.Interfaces.dll`

== Синтаксис

[source,csharp]
----
public interface IReplicationService
----

== Методы

[cols=",",options="header"]
|===
|Имя |Описание

|`EnqueueEvents` |Запускает обработку очереди событий МФО.
|`FindScheduledTasks(Guid)`
a|Выполняет поиск исходящих заданий интеграции для указанного удаленного сервера.

.Параметры:
* `forReceiverServerId` -- идентификатор сервера-получателя

*Тип*: `IEnumerable<CardData>` -- коллекция карточек.

|`HandleEvent(IEventQueueItem, Boolean)`
a|Обрабатывает элемент очереди событий.

.Параметры:
* `eventQueueItem` -- событие обмена
* `throwExceptions` -- флаг, указывающий на необходимость возврата исключения при возникновении ошибки

*Тип*: `System.Boolean`. Результат обработки: `true` -- успешно, иначе -- `false`

|`ImportIntegrationTasks(Boolean)`
a|Выполняет загрузку необработанных входящих _Заданий интеграции_.

.Параметры:
* `ignoreExceptions` -- `true`, если следует продолжать загрузку при возникновении ошибки

|`ImportIntegrationTasksPacket(String)`
a|Выполняет загрузку упакованного _Задания интеграции_, представленного в виде строки.

.Параметры:
* `data` -- данные _Задания интеграции_

|`ReplicateConfirmedTasks(IReplicationTransfer, Guid)`
a|Выполняет обработку входящий _Заданий интеграции_, формирует пакет подтверждения получения и отправляет ответ серверу-отправителю задания.

.Параметры:
* `transfer` -- реализация транспорта, осуществляющего передачу данных
* `forReceiverServerId` -- идентификатор сервера {dv}, которому предназначается ответ

|`ReplicateIntegrationTask(IReplicationTransfer, Guid, CardData, Func<Boolean>)`
a|Выполняет отправку отдельного _Задания интеграции_.

.Параметры:
* `transfer` -- реализация транспорта, осуществляющего передачу данных
* `forReceiverServerId` -- идентификатор удаленного сервера {dv}
* `card` -- отправляемое Задание интеграции
* `isCancelling` -- необязательная функция, вызываемая на некоторых этапах обработки Заданий интеграции, которая позволяет прервать выполнение (должна вернуть `true`)

|`ReplicateIntegrationTasks(IReplicationTransfer, Guid`)
a|Выполняет отправку исходящих _Заданий интеграции_.

.Параметры:
* `transfer` -- реализация транспорта, осуществляющего передачу данных
* `forReceiverServerId` -- идентификатор удаленного сервера

|===

== Примеры

[source,csharp]
----
SessionManager sessionManager = SessionManager.CreateInstance(dvServerUrl); <.>
UserSession userSession = sessionManager.CreateSession();
var sessionContainer = new System.ComponentModel.Design.ServiceContainer();
sessionContainer.AddService(typeof({dv}.Platform.ObjectManager.UserSession), userSession);

ObjectContext objectContext = new ObjectContext(sessionContainer); <.>
objectContext.AddService<IPersistentStore>({dv}ObjectFactory.CreatePersistentStore(new SessionProvider(userSession), null));

var serviceFactoryRegistry = objectContext.GetService<IServiceFactoryRegistry>(); <.>
var mapperFactoryRegistry = objectContext.GetService<IObjectMapperFactoryRegistry>();

mapperFactoryRegistry.RegisterFactory(typeof(ReplicationMapperFactory)); <.>
            
serviceFactoryRegistry.RegisterFactory(typeof(ReplicationExtensibilityServiceFactory)); <.>
            
IReplicationService iReplicationService = objectContext.GetService<IReplicationService>(); <.>

iReplicationService.EnqueueEvents(); <.>
----
<.> Создание пользовательской сессии.
<.> Инициализация контекста.
<.> Получения сервис-реестров.
<.> Добавления фабрики преобразователей данных МФО.
<.> Добавление фабрики дополнительных сервисов МФО.
<.> Получение сервиса обработки Заданий интеграции.
<.> Запуск обработки очереди событий.
