= IReplicationSettingsService - интерфейс

Интерфейс IReplicationSettingsService определяет методы, предоставляемые сервисом для работы со _Справочником настроек МФО_.

* *Пространство имен:* {dv}.Replication.ObjectModel.Services
* *Сборка:* `{dv}.Replication.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
public interface IReplicationSettingsService
----

== Методы

[cols="41%,59%",options="header"]
|===
|Имя |Описание
|AddNewExchangeScenario a|
Добавляет новый _сценарий обмена_.

Тип: List<xref:IExchangeScenario_IN.adoc[IExchangeScenario]>

|DeleteExchangeScenario (IExchangeScenario) a|
Удаляет существующий _сценарий обмена_.

Параметры:

* exchangeScenario - удаляемый сценарий обмена

|GetConflictHandlers a|
Возвращает описание доступных _компонентов разрешения конфликтов_. _Не используется в текущей реализации._

Тип: List<xref:HandlerInfo_CL.adoc[HandlerInfo]>

|GetExchangeScenarios a|
Возвращает доступные сценарии обмена.

Тип: List<xref:IExchangeScenario_IN.adoc[IExchangeScenario]>

|GetExportDatasetHandlers a|
Возвращает описание доступных _компонентов определения состава передачи_.

Тип: List<xref:HandlerInfo_CL.adoc[HandlerInfo]>

|GetExportHandlers a|
Возвращает описание доступных _компонентов выгрузки_.

Тип: List<xref:HandlerInfo_CL.adoc[HandlerInfo]>

|GetImportHandlers a|
Возвращает описание доступных _компонентов загрузки данных_.

Тип: List<xref:HandlerInfo_CL.adoc[HandlerInfo]>

|GetRecepientsHandlers a|
Возвращает описание доступных _компонентов определения адресатов_.

Тип: List<xref:HandlerInfo_CL.adoc[HandlerInfo]>

|===

== Примеры

Следующий код демонстрирует пример использования сервиса управления сценариями обмена.

[source,pre,codeblock,language-csharp]
----
//Создание пользовательской сессии
SessionManager sessionManager = SessionManager.CreateInstance(dvServerUrl);
UserSession userSession = sessionManager.CreateSession();
var sessionContainer = new System.ComponentModel.Design.ServiceContainer();
sessionContainer.AddService(typeof({dv}.Platform.ObjectManager.UserSession), userSession);

//Инициализация контекста
ObjectContext objectContext = new ObjectContext(sessionContainer);
objectContext.AddService<IPersistentStore>({dv}ObjectFactory.CreatePersistentStore(new SessionProvider(userSession), null));

// Получения сервис-реестров
var serviceFactoryRegistry = objectContext.GetService<IServiceFactoryRegistry>();
var mapperFactoryRegistry = objectContext.GetService<IObjectMapperFactoryRegistry>();

// Добавления фабрики преобразователей данных МФО
mapperFactoryRegistry.RegisterFactory(typeof(ReplicationMapperFactory));
            
// Добавление фабрики сервисов МФО
serviceFactoryRegistry.RegisterFactory(typeof(ReplicationServiceFactory));
            
// Получение сервиса для работы со сценариями обмена
IReplicationSettingsService iReplicationSettingsService = objectContext.GetService<IReplicationSettingsService>();

// Регистрация нового сценария обмена
ExchangeScenario exchangeScenario = (ExchangeScenario)iReplicationSettingsService.AddNewExchangeScenario();

// Передаем полное название классов компонентов обмена
exchangeScenario.ExportDatasetHandler = "Replication.DataExporters.ExportDataset";
exchangeScenario.ExportHandler = "Replication.DataExporters.Export";
exchangeScenario.ImportHandler = "Replication.DataImporters.Import";
exchangeScenario.RecipientsHandler = "Replication.DataExporters.Recipients";

// Идентификатор вида карточки, для которого разрабатывается сценарий обмена
exchangeScenario.Kind = new Guid("8E40F327-9517-4A43-998D-BF2BD619588D");

// Название сценария обмена
exchangeScenario.Name = "Сценарий для исходящего документа";

// Обязательное сохранение
objectContext.SaveObject<ExchangeScenario>(exchangeScenario);
----
