= Разработка компонента определения состава передачи

_Компонент определения состава передачи_ должен предоставить список идентификаторов карточек, которые должны быть переданы на удаленные сервера {dv}.

Программный класс данного должен реализовывать интерфейс xref:IEventResolver_IN.adoc[IEventResolver] с единственным методом [.keyword .apiname]#ResolveEvent#. Данный метод должен добавить идентификаторы отправляемых карточек в переменную `Cards` объекта e, переданного в первом параметре метода.

Список отправляемых данных должен быть минимально достаточным, т. к. большое число передаваемых данных скажется на конечной производительности, а недостаточность этих данных – на невозможности работы с карточками.

Следующий код демонстрирует пример реализации _компонента определения состава передачи_, в котором в пакет отправляемых данных добавляется только карточка, из которой было вызвано событие обмена.

[source,pre,codeblock,language-csharp]
----
using {dv}.Replication.Extensibility;
using {dv}.Replication.Interfaces;

namespace Replication.Demo
{

    // Описание, переданное в DescriptionAttribute, будет выводиться в 
    //  выпадающем списке Справочника настроек МФО
    [ResName("Пример. Определение состава передачи")]
    public class EventResolver : BaseHandler, IEventResolver
    {
        public void ResolveEvent(IExchangeEvent e, out bool cancel)
        {

        // Если в списке карточек отсутствует карточка вызвавшая событие,
        //  то она будет добавлена
        if (!e.Cards.Contains(e.ObjectId))
        {
            e.Cards.Add(e.ObjectId);
        }

        // Обработку не останавливать
        cancel = false;
        }
    }
}
----
