= Разработка компонента определения адресатов

_Компонент определения адресатов_ должен сформировать список идентификаторов серверов {dv}, которым требуется разослать синхронизируемые карточки.

Компонент определения адресатов должен реализовывать интерфейс xref:IRecipientResolver_IN.adoc[IRecipientResolver] с единственным методом [.keyword .apiname]#ResolveEvent#, при вызове которого переданная в метод переменная `e.Recipients` должна быть заполнена идентификаторами серверов-получателей.

Следующий код демонстрирует пример реализации компонента определения адресатов, который добавляет в список получателей сервер {dv}, на котором зарегистрирован сотрудник, являющийся автором синхронизируемого задания. Пример сценария: задание было изменено (например, выполнено) на удаленном сервере {dv} и данные изменения должны попасть на сервер автора задания.

[source,pre,codeblock,language-csharp]
----
using {dv}.Replication.Extensibility;
using {dv}.Replication.Interfaces;
using {dv}.BackOffice.CardLib.CardDefs;
using {dv}.BackOffice.ObjectModel;
using {dv}.Platform.ObjectManager;
using System;

namespace Replication.Demo
{

 // Описание, переданное в DescriptionAttribute, будет выводиться
 //  в выпадающем списке Справочника настроек МФО
 [ResName("Пример. Определение адресатов")]
 public class RecipientResolver : BaseHandler, IRecipientResolver
 {

  // Параметр e содержит данные добавляемого события
  // Параметр cancel определяет необходимость остановки дальнейшей обработки события обмена:
  //  установите cancel в значение true, чтобы событие обмена дальше не обрабатывалось
  public void ResolveEvent(IExchangeEvent e, out bool cancel)
  {

   // Получаем из события обмена идентификатор карточки, из которой вызвано событие
   // В данном случае, это карточка Задание
   var task = Context.GetObject<Task>(e.ObjectId);

   // Получаем Справочник сотрудников
   CardData refStaff = UserSession.CardManager.GetDictionaryData(RefStaff.ID);

   // Получаем идентификатор сотрудника, являющегося автором задания
   RowData rowRefStaff = refStaff.Sections[RefStaff.Employees.ID].GetRow(Context.GetObjectRef(task.MainInfo.Author).Id);
  
   // Получаем идентификатор сервера-владельца записи сотрудника
   Guid ownServerID = rowRefStaff.GetGuid("OwnServerID") ?? Guid.Empty;

   // Получаем идентификатор текущего сервера, чтобы убедиться,  что автор задания 
   // не зарегистрирован на текущем сервере(тогда межфилиальный обмен не потребуется)
   Guid currentServerId = new Guid((base.UserSession.Properties["ServerID"].Value as string));
   
   // Если сервер получателя не определен, либо совпадает с текущим, 
   //  то обработка будет прервана
   cancel = (ownServerID = Guid.Empty || ownServerID = currentServerId);
            
   if (!cancel)
   {
    // Добавляем идентификатор сервера-владельца записи сотрудника
    e.Recipients.Add(ownServerID);
   }
  }
 }
}
----
