[[ariaid-title1]]
== Настройка Справочника видов карточек

Межфилиальный обмен начинается с запуска экземпляра БП «Регистрация события МФО», который осуществляется при наступлении определённого события карточки.

Базовые сценарии межфилиального обмена предусматривают несколько событий начала межфилиального обмена, при котором будут запущены БП «Регистрация события МФО»:

* Для вида [.ph .filepath]`Задание → Задание УД → На исполнение` обмен запускают БП:
** «Регистрация события МФО: задание отозвано»,
** «Регистрация события МФО: задание отклонено»,
** «Регистрация события МФО: задание в работе»,
** «Регистрация события МФО: задание делегировано»,
** «Регистрация события МФО: задание на приёмку»,
** «Регистрация события МФО: задание на доработку»,
** «Регистрация события МФО: завершено задание»,
** «Регистрация события МФО: запущено задание».
* Для вида [.ph .filepath]`Задание → Задание КС → На подписание` обмен запускает БП «Регистрация события МФО: Подписание».
* Для вида [.ph .filepath]`Задание → Задание КС → На консолидацию` обмен запускает БП «Регистрация события МФО: Консолидация».
* Для вида [.ph .filepath]`Задание → Задание КС → На согласование` обмен запускает БП «Регистрация события МФО: Согласование».
* Для вида [.ph .filepath]`Документ → ДокументУД → ОРД` обмен запускает БП «Регистрация события МФО: Репликация ОРД».

Для возможности запуска указанных БП из карточек документа и задания необходимо предоставить права на запуск требуемым пользователям:

. Откройте [.dfn .term]_Справочник видов карточек_;
. Откройте настройки вида [.ph .filepath]`Задание → Задание УД → На исполнение`.
. Из раздела «Процессы» откройте настройки БП, реализующего запуск регистрации события, например: «Регистрация события МФО: задание отозвано».
. В настройке «Права на запуск бизнес-процесса» выберите роли, сотрудники которых могут осуществлять регистрацию, изменение или исполнение соответствующих заданий или документов. Например: «Автор», «Ответственный исполнитель» и др.
. Сохраните настройки вида карточек.
. Аналогичным образом выдайте права для всех БП, перечисленных выше, на всех серверах Docsvision, участвующих в межсерверном обмене.

*На уровень выше:* xref:../topics/HowConfig.adoc[Подготовка к работе]
