[[ariaid-title1]]
== Настройка Справочника сотрудников

Если в организации используется [.dfn .term]_Модуль репликации справочников_, то настройки, перечисленные в данном пункте, уже были выполнены. В этом случае рекомендуется убедиться, что всё верно – повторно выполнять настройку не требуется. Для проверки откройте в Docsvision Explorer (входит в комплект инструментов разработчика «Docsvision 5 Resource Kit») Справочник сотрудников и убедитесь, что в поле «OwnerServerID» у сотрудников указан идентификатор сервера Docsvision, на котором работает данный сотрудник. Идентификатор сервера Docsvision был получен в пункте xref:HowConfigInstallPB1.adoc[Настройка Справочника серверов].

Если [.dfn .term]_Модуль репликации справочников_ не используется, необходимо привязать существующих сотрудников к серверам Docsvision, на которых сотрудники работают. Новые сотрудники будут привязываться автоматически.

. Используйте предложенный скрипт привязки сотрудников в БД Docsvision.
+
Ниже приведены скрипты, которые можно использовать для привязки определённого сотрудника, всех сотрудников определённого подразделения/организации или всех сотрудников из Справочника сотрудников.
+
* Следующий скрипт привязывает к серверу всех сотрудников из Справочника сотрудников. В переменной `@ServerID` нужно указать идентификатор сервера Docsvision, к которому выполняется привязка.
+
[source,pre,codeblock]
----
DECLARE @ServerID uniqueidentifier

-- Укажите здесь идентификатор сервера Docsvision, определенный из Справочника серверов
SET @ServerID = '00000000-0000-0000-0000-000000000000'

EXECUTE [dbo].[dvreport_get_data_{b79976ed-510b-47b6-983d-558b5634c65a}] 
    @ServerID
GO
----
* Следующий скрипт привязывает к серверу сотрудников подразделения. Привязка сотрудников подчинённых подразделений/организаций не осуществляется. В переменной `@ServerID` нужно указать идентификатор сервера Docsvision, к которому выполняется привязка, в `@UnitID` – идентификатор подразделения или организации.
+
[source,pre,codeblock]
----
DECLARE @ServerID uniqueidentifier
DECLARE @UnitID uniqueidentifier

-- Укажите здесь идентификатор сервера Docsvision, определенный из Справочника серверов
SET @ServerID = '00000000-0000-0000-0000-000000000000'

-- Укажите здесь идентификатор подразделение, которому производится привязка к серверу
SET @UnitID = '00000000-0000-0000-0000-000000000001'

EXECUTE [dbo].[dvreport_get_data_{76fcd442-4ebe-4b62-9bd3-404f33475dc2}] 
    @ServerID,@UnitID
GO 
----
* Следующий скрипт привязывает к серверу определённого сотрудника. В переменной `@ServerID` нужно указать идентификатор сервера Docsvision, к которому выполняется привязка, в `@EmployeeID` – идентификатор сотрудника.
+
[source,pre,codeblock]
----
DECLARE @ServerID uniqueidentifier
DECLARE @EmployeeID uniqueidentifier

-- Укажите здесь идентификатор сервера Docsvision, определенный из Справочника серверов
SET @ServerID = '00000000-0000-0000-0000-000000000000'

-- Укажите здесь идентификатор сотрудника, которому производится привязка к серверу
SET @EmployeeID = '00000000-0000-0000-0000-000000000001'

EXECUTE [dbo].[dvreport_get_data_{f21db176-2dc5-4ba0-8053-3e10a8489fb9}] 
    @ServerID,@EmployeeID
GO
----
+
После выполнения скрипта убедитесь, что сотрудники были привязаны к серверу Docsvision: используя Docsvision Explorer выборочно проверьте значение поля `OwnServerID` у сотрудников. Значение должно соответствовать идентификатору сервера Docsvision.
. Выполните аналогичную операцию на всех серверах Docsvision, участвующих в межсерверном обмене.
+
После того, как процедура настройки будет завершена на всех серверах Docsvision, необходимо синхронизировать [.dfn .term]_Справочники сотрудников_ серверов Docsvision – перенести данные каждого сервера на другие сервера, а также обеспечить их последующую синхронизацию.

*На уровень выше:* xref:../topics/HowConfig.adoc[Подготовка к работе]
