[[ariaid-title1]]
== Описание работы БП «Обработка очереди сообщений МФО»

БП «Обработка очереди сообщений МФО» выполняет следующие операции:

. Проверяет [.dfn .term]_очередь событий_ на наличие необработанных (статус обработки события «Не обработано»/«Unhandled») [.dfn .term]_событий обмена_.
. При обнаружении нового [.dfn .term]_события обмена_:
[loweralpha]
.. Определяются [.dfn .term]_получатели_ синхронизируемых карточек.
+
Список [.dfn .term]_получателей_ предоставляет [.dfn .term]_компонент определения адресатов_, указанный в текущем [.dfn .term]_сценарии обмена_. В стандартной реализации [.dfn .term]_компонент определения адресатов_ получает идентификатор из поля `OwnServerID` [.dfn .term]_карточки сотрудника_, указанного в синхронизируемой карточке.
.. Определяются карточки, которые требуется передать на удаленные сервера.
+
Список карточек предоставляет [.dfn .term]_компонент определения состава передачи_, указанный в текущем [.dfn .term]_сценарии обмена_. В стандартной реализации [.dfn .term]_компонент определения состава передачи_ включает в список карточку, вызвавшую [.dfn .term]_событие обмена_, а также связанные карточки до заданного уровня вложенности.
.. Выгружается содержимое отправляемых карточек.
+
Содержимое карточек выгружает [.dfn .term]_компонент выгрузки_, указанный в текущем [.dfn .term]_сценарии обмена_. Указанный компонент следует собственной логике выгрузки, как правило, в пакет включаются карточки, полученные на предыдущем шаге, и атрибуты приложенных к карточкам файлов (без бинарного содержимого).
.. Для каждого сервера-получателя формируется [.dfn .term]_Задание интеграции_ с содержимым карточек для отправки на удаленный сервер.
+
В карточку Задания интеграции записывается информация об отправителе и получателе, идентификатор карточки, вызвавшей [.dfn .term]_событие обмена_, идентификатор [.dfn .term]_сценария обмена_ и файлы:

* файл в формате XML с содержимым карточек;
* файлы в бинарном формате c содержимым файлов.
+
Для файлов значение статуса переноса устанавливается в «Нужен перенос»/«NeedTransfer».
+
Для карточки задания статус задания на площадке-отправителе устанавливается в «Создано»/«Scheduled».
+
После завершения работы статус обработки события обмена может принимать значения:

* «Обработано»/«Handled» – если в результате работы сформированы [.dfn .term]_Задания интеграции_;
* «Отменено»/«Cancelled» – если обработка события пропущена (например, если нет [.dfn .term]_получателей_ или нет отправляемых карточек) и [.dfn .term]_Задания интеграции_ не сформированы;
* «Ошибка»/«Error» – если в процессе обработки события возникала ошибка и [.dfn .term]_Задания интеграции_ не сформированы.

*На уровень выше:* xref:../topics/Structure.adoc[Структура модуля]
