[[ariaid-title1]]
== Необходимое программное обеспечение

[[Required_resources_software.dita__section_ffy_3t2_djb]]
=== Требования серверной части Модуля

. *Модули Docsvision*:
[loweralpha]
.. Серверная часть модуля «Docsvision 5. Платформа» версии 5.5.1 и выше.
.. Серверная часть приложения «Docsvision 5. Управление документами» версии 5.5.1 и выше.
.. Серверная часть модуля «Docsvision 5. Управление процессами» версии 5.5.1 и выше.
.. Серверная часть модуля «Docsvision 5. Конструктор согласований» версии 5.5.1 и выше.
.. Серверная часть приложения «Docsvision 5. Делопроизводство 4.5» версии 5.5.1 и выше.
.. Серверная часть модуля «Docsvision 5. Windows-клиент» версии 5.5.1 и выше.

[[Required_resources_software.dita__section_ify_3t2_djb]]
=== Требования клиентской части Модуля

. *Модули Docsvision*:
[loweralpha]
.. Клиентская часть модуля «Docsvision 5. Платформа» версии 5.5.1 и выше.
.. Клиентская часть приложения «Docsvision 5. Управление документами» версии 5.5.1 и выше.
.. Клиентская часть модуля «Docsvision 5. Управление процессами» версии 5.5.1 и выше.
.. Клиентская часть модуля «Docsvision 5. Конструктор согласований» версии 5.5.1 и выше.
.. Клиентская часть приложения «Docsvision 5. Делопроизводство 4.5» версии 5.5.1 и выше.
.. Клиентская часть модуля «Docsvision 5. Windows-клиент» версии 5.5.1 и выше.

* *xref:../topics/DirectoryReplication.adoc[Модуль репликации справочников]* +

*Parent topic:* xref:../topics/Required_resources.adoc[Необходимые ресурсы]
