[[ariaid-title1]]
== Предоставление прав службе Workflow

Для выполнения задач межфилиального обмена учётной записи службы Workflow должны быть предоставлены права администратора Docsvision.

Полный список требований МФО к учётной записи Workflow:

. На сервере Docsvision:
* включена в локальные группы безопасности «Docsvision Administrators» и «Performance Monitor Users».
. На компьютере с серверной частью Модуля:
* включена в локальную группу «Users»,
* предоставлено право "Log on as service" в локальной политике безопасности,
* предоставлены права на чтение и запись в ветку реестра HKLM\Software\Docsvision\Workflow.
. Предоставлены +++полные+++ права по дискреционной модели безопасности на все папки и справочники системы Docsvision.
. В Справочнике сотрудников создан сервисный пользователь с учётной записью сервиса Workflow и данный пользователь включен в группу сотрудников «Системная для WF».

Перечисленные права должны быть предоставлены учётной записи Workflow на всех серверах Docsvision, участвующих в обмене.

*Parent topic:* xref:../topics/HowConfig.adoc[Подготовка к работе]
