= Приложение A.3. Передача статических документов УД

Сценарий "Распределенное исполнение заданий" реализует отправку документов сотрудникам, находящимся в удаленных офисах. Данный сценарий формируется с использованием сценария "Репликация ОРД".

== Сценарий "Репликация ОРД"

Данный сценарий обеспечивает простую передачу карточки _Документ_ на удаленный сервер. Запуск сценария осуществляется при переходе документа в статус:

* "Действует",
* "В Архив".

.Описание сценария обмена
[cols="34%,66%",options="header"]
|===
|Этап |Действие
|Определение адресатов |Все сервера, кроме текущего.
|Определение состава передачи a|
В выгрузку включена карточка документа и связанные с ней:

* карточка файла с версиями;
* список ссылок на карточки заданий (без самих заданий);
* список подписей и сами подписи;
* список категорий и сами категории.

|Выгрузки |Формирует из каждой карточки, подготовленной к отправке, xml-документ.
|Загрузки |Осуществляет перезапись существующих данных.
|===

При возникновении конфликтных ситуаций будет произведена перезапись данных карточек. Кроме основной карточки, _получателю_ также передаются связанные карточки файлов.
