= Описание работы БП "Обработка очереди входящих заданий МФО"

БП "Обработка очереди входящих заданий МФО" выполняет следующие операции:

. Выполняет поиск полученных Заданий интеграции со статусом задания на площадке-получателе "Получено" или "Обработка остановлена из-за блокировки".
. При обнаружении подходящих карточек:
[loweralpha]
.. Выгружает из Задания интеграции пакет с данными карточек и атрибутами файлов карточек.
.. Проверяет возможность загрузки полученного пакета и загружает данные в базу данных. Проверка и загрузка осуществляются с использованием _компонента загрузки_, который указан в текущем _сценарии обмена_.
.. Загружает бинарные данные файлов в базу данных.
+
Статус переноса файла после завершения загрузки может принять одно из следующих значений:

* "Завершен"/"Finished" – файл успешно загружен;
* "Заблокирован на удалённом сервере"/"Locked" – если существует другая версия файла и она заблокирована.
+
Если обнаружены заблокированные файлы, дальнейшая работа обработчика будет остановлена до следующего запуска.
.. Загружает в базу данных пакет с данными карточек и атрибутами файлов.
+
Статус задания на площадке-получателе после завершения загрузки может принять одно из следующих значений:

* "Успешно обработано загрузчиком"/"Handled" – если данные успешно загружены;
* "Обработка остановлена из-за блокировки"/"Locked" – если существует другая версия карточки и она заблокирована;
* "При обработке произошла ошибка"/"Error" – если при загрузке данных произошла ошибка.
.. Запускает бизнес-процесс пост-обработки, если он указан в текущем _сценарии обмена_.
