= Настройка Справочника видов карточек

Межфилиальный обмен начинается с запуска экземпляра БП _Регистрация события МФО_, который осуществляется при наступлении определённого события карточки.

Базовые сценарии межфилиального обмена предусматривают несколько событий начала межфилиального обмена, при котором будут запущены БП _Регистрация события МФО_:

* Для вида menu:Задание[Задание УД > На исполнение] обмен запускают БП:
+
** _Регистрация события МФО: задание отозвано_
** _Регистрация события МФО: задание отклонено_
** _Регистрация события МФО: задание в работе_
** _Регистрация события МФО: задание делегировано_
** _Регистрация события МФО: задание на приёмку_
** _Регистрация события МФО: задание на доработку_
** _Регистрация события МФО: завершено задание_
** _Регистрация события МФО: запущено задание_
+
* Для вида menu:Задание[Задание КС > На подписание] обмен запускает БП _Регистрация события МФО: Подписание_.
* Для вида menu:Задание[Задание КС > На консолидацию] обмен запускает БП _Регистрация события МФО: Консолидация_.
* Для вида menu:Задание[Задание КС > На согласование] обмен запускает БП _Регистрация события МФО: Согласование_.
* Для вида menu:Документ[ДокументУД > ОРД] обмен запускает БП _Регистрация события МФО: Репликация ОРД_.

Для возможности запуска указанных БП из карточек документа и задания необходимо предоставить права на запуск требуемым пользователям:

. Откройте _Справочник видов карточек_.
. Откройте настройки вида menu:Задание[Задание УД > На исполнение].
. Из раздела _Процессы_ откройте настройки БП, реализующего запуск регистрации события, например: _Регистрация события МФО: задание отозвано_.
. В настройке _Права на запуск бизнес-процесса_ выберите роли, сотрудники которых могут осуществлять регистрацию, изменение или исполнение соответствующих заданий или документов. Например: _Автор_, _Ответственный исполнитель_ и др.
. Сохраните настройки вида карточек.
. Аналогичным образом выдайте права для всех БП, перечисленных выше, на всех серверах {dv}, участвующих в межсерверном обмене.
