= Просмотр очереди событий

Данные очереди событий хранятся в таблице `dvtable_\{ab71cdbf-71ee-410b-bcde-928dbc1afc9d}` БД {dv}.

Наиболее интересные столбцы таблицы `dvtable_\{ab71cdbf-71ee-410b-bcde-928dbc1afc9d}`:

* ItemID – идентификатор события;
* EventTypeId – идентификатор _сценария обмена_;
* ObjectId – идентификатор карточки, инициировавшей создание события;
* EventDateTime – время добавления события;
* State – статус события:
** 0 – не обработано;
** 1 – обработано;
** 2 – ошибка;
** 3 – отменено.
* Details – дополнительные сведения, необходимые для обработки события;
* Log – результат обработки события в виде строки.

Ниже приведён пример SQL-скрипта, возвращающего все необработанные события обмена (State равен 0) текущего дня:

[source]
----
SELECT TOP 100 * FROM [dvtable_{ab71cdbf-71ee-410b-bcde-928dbc1afc9d}] WITH (NOLOCK)
   WHERE [EventDateTime]>cast(getdate() as date) AND [State] = 0
----

[NOTE]
====
При формировании запроса рекомендуется ограничивать количество возвращаемых значений и отключить блокировку строк при чтении.
====
