= Описание работы БП "Обработка очереди сообщений МФО"

БП "Обработка очереди сообщений МФО" выполняет следующие операции:

. Проверяет _очередь событий_ на наличие необработанных (статус обработки события "Не обработано"/"Unhandled") _событий обмена_.
. При обнаружении нового _события обмена_:
[loweralpha]
.. Определяются _получатели_ синхронизируемых карточек.
+
Список _получателей_ предоставляет _компонент определения адресатов_, указанный в текущем _сценарии обмена_. В стандартной реализации _компонент определения адресатов_ получает идентификатор из поля `OwnServerID` _карточки сотрудника_, указанного в синхронизируемой карточке.
.. Определяются карточки, которые требуется передать на удаленные сервера.
+
Список карточек предоставляет _компонент определения состава передачи_, указанный в текущем _сценарии обмена_. В стандартной реализации _компонент определения состава передачи_ включает в список карточку, вызвавшую _событие обмена_, а также связанные карточки до заданного уровня вложенности.
.. Выгружается содержимое отправляемых карточек.
+
Содержимое карточек выгружает _компонент выгрузки_, указанный в текущем _сценарии обмена_. Указанный компонент следует собственной логике выгрузки, как правило, в пакет включаются карточки, полученные на предыдущем шаге, и атрибуты приложенных к карточкам файлов (без бинарного содержимого).
.. Для каждого сервера-получателя формируется _Задание интеграции_ с содержимым карточек для отправки на удаленный сервер.
+
В карточку Задания интеграции записывается информация об отправителе и получателе, идентификатор карточки, вызвавшей _событие обмена_, идентификатор _сценария обмена_ и файлы:

* файл в формате XML с содержимым карточек;
* файлы в бинарном формате c содержимым файлов.
+
Для файлов значение статуса переноса устанавливается в "Нужен перенос"/"NeedTransfer".
+
Для карточки задания статус задания на площадке-отправителе устанавливается в "Создано"/"Scheduled".
+
После завершения работы статус обработки события обмена может принимать значения:

* "Обработано"/"Handled" – если в результате работы сформированы _Задания интеграции_;
* "Отменено"/"Cancelled" – если обработка события пропущена (например, если нет _получателей_ или нет отправляемых карточек) и _Задания интеграции_ не сформированы;
* "Ошибка"/"Error" – если в процессе обработки события возникала ошибка и _Задания интеграции_ не сформированы.
