[[ariaid-title1]]
== FileReplicationTransfer - класс

Класс FileReplicationTransfer предоставляет метод записи [.dfn .term]_Задания интеграции_, подготовленного к отправке на удаленный сервер, в файл.

* [.keyword]*Пространство имен:* Docsvision.Replication.Extensibility.Transfers
* [.keyword]*Сборка:* [.ph .filepath]`Docsvision.Replication.Extensibility.dll`

=== Синтаксис

[source,pre,codeblock,language-csharp]
----
public class FileReplicationTransfer : IReplicationTransfer
----

=== Конструкторы

[width="99%",cols="34%,66%",options="header",]
|===
|Имя |Описание
|FileReplicationTransfer(String, Guid) a|
Инициализирует новый экземпляр класса FileReplicationTransfer.

Параметры:

* basePath - полный путь для выгрузки файла
* remoteServerId - идентификатор удаленного сервера

|===

=== Свойства

[width="99%",cols="34%,66%",options="header",]
|===
|Имя |Описание
|RemoteServerId |Возвращает идентификатор удаленного сервера. Тип System.Guid.
|===

=== Методы

[width="99%",cols="34%,66%",options="header",]
|===
|Имя |Описание
|Transfer(String) a|
Передает на удаленный сервер Docsvision [.dfn .term]_Задание интеграции_, содержащее данные карточек, атрибуты файлов карточек и бинарные данные файлов.

Параметры:

* data - строка, содержащая XML данные карточки [.dfn .term]_Задания интеграции_

|TransferIntegrationTask(Guid, String) |_Не используется в текущей реализации. При попытке обращения будет возвращено исключение._
|TransferIntegrationTaskFile(Guid, Guid, FileData, ref Boolean) |_Не используется в текущей реализации. При попытке обращения будет возвращено исключение._
|===

=== Заметки

Итоговый файл будет сформирован по следующему пути [.ph .filepath]`\{basePath}/\{remoteServerId}/\{yyMMddhhmmss}.xml`, где:

* `basePath` – значение параметра `basePath`, переданного в конструктор класса;
* `remoteServerId` – значение параметра `remoteServerId`, переданного в конструктор класса и приведенного к строковому виду;
* `yyMMddhhmmss` – текущее время, приведенное к формату «yyMMddhhmmss».

=== Примеры

Далее приведена часть бизнес-процесса "Выгрузка данных удаленному серверу XX", который отвечает за передачу [.dfn .term]_Задания интеграции_ удаленному серверу. Данный экземпляр бизнес-процесса выполняет запись заданий в папку [.ph .filepath]`Z:\Export` (полный путь будет сформирован по правилу, описанному выше). Предполагается, что [.dfn .term]_получатель_ самостоятельно запросит содержимое нужной папки и выполнит обработку имеющихся там [.dfn .term]_Заданий интеграции_.

[source,pre,codeblock,language-csharp]
----
/*
 Начало скрипта бизнес-процесса "Выгрузка данных удаленному серверу XX" совпадает с шаблоном "Выгрузка данных удаленному серверу"
*/

// Получение сервиса репликации
IReplicationLibService replicationLibService = Context.GetService<IReplicationLibService>();

// Инициализация класса, отвечающего за передачу Задания интеграции. remoteServerID - идентификатор удаленного сервера (получен из параметров бизнес процесса)
FileReplicationTransfer transfer = new FileReplicationTransfer(@"z:\export", remoteServerID);

// Выполнение передачи задания           
replicationLibService.ReplicateIntegrationTasks(transfer, remoteServerID);
----

На стороне [.dfn .term]_получателя_ необходимо осуществить загрузку заданий из папки, в которую осуществляется сброс [.dfn .term]_Заданий интеграции_. В простейшем случае код бизнес-процесса, осуществляющего загрузку одного задания будет выглядеть следующим образом:

[source,pre,codeblock,language-csharp]
----
using System;
using System.Xml;

using DocsVision.Workflow.Objects;
using DocsVision.Workflow.Runtime;
using DocsVision.Workflow.Gates;
using DocsVision.Platform.HelperAPI;
using DocsVision.Platform.ObjectManager;

namespace DVScriptHost
{
 class DVScript
 {
  public void Execute (ProcessInfo process, PassState passInfo)
  {

   // Путь к файлу, содержащему выгрузку карточки Задание интеграции. 313f9565-c312-47fb-bf6f-b35d9e2949e9 - идентификатор сервера получателя
   string data = System.IO.File.ReadAllText(@"z:\export\{313f9565-c312-47fb-bf6f-b35d9e2949e9}\141014031005.xml");
   
   // Вызов серверного метода, выполняющего загрузку Заданий интеграции
   ExtensionMethod extensionMethod = process.Session.ExtensionManager.GetExtensionMethod("ReplicationServerExtension", "ImportIntegrationTasks");
   extensionMethod.Parameters.AddNew("data", ParameterValueType.String, data);
   extensionMethod.Execute();
  }
 }
}
----

*На уровень выше:* xref:../topics/API.adoc[Описание API Модуля]
