[[ariaid-title1]]
== IDataExporter - интерфейс

Описывает сигнатуру класса [.dfn .term]_компонента выгрузки_, отвечающего за выгрузку данных карточке на стороне [.dfn .term]_отправителя_.

* [.keyword]*Пространство имен:* Docsvision.Replication.Interfaces
* [.keyword]*Сборка:* [.ph .filepath]`Docsvision.Replication.Interfaces.dll`

=== Синтаксис

[source,pre,codeblock,language-csharp]
----
public interface IDataExporter
----

=== Методы

[width="100%",cols="38%,62%",options="header",]
|===
|Имя |Описание
|GetCardXml(IExchangeEvent, Stream, out IEnumerable<Guid>, out Boolean) a|
При переопределении в производном классе сохраняет данные передаваемой на удаленный сервер Docsvision карточки в поток.

Параметры:

* e – данные события обмена
* writeSteam – поток для записи выгружаемых данных карточек
* fileIds – идентификаторы выгруженных файлов
* handled – если флаг установлен в false, то после вызова метода GetCardXml будет выполнена попытка использовать стандартный способ экспорта данных карточки.

|===

=== Заметки

Пример реализации смотрите в разделе xref:UseAPIDataExporter.adoc[Разработка компонента выгрузки].

*На уровень выше:* xref:../topics/API.adoc[Описание API Модуля]
